on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies manually
        run: |
          sudo apt update
          sudo apt install -y wget

          # Download .deb files
          wget http://security.ubuntu.com/ubuntu/pool/universe/n/ncurses/libncurses5_6.2-0ubuntu2_amd64.deb
          wget http://security.ubuntu.com/ubuntu/pool/universe/n/ncurses/libtinfo5_6.2-0ubuntu2_amd64.deb

          # Install the packages
          sudo dpkg -i libncurses5_6.2-0ubuntu2_amd64.deb || true
          sudo dpkg -i libtinfo5_6.2-0ubuntu2_amd64.deb || true

          # Fix broken dependencies
          sudo apt-get install -f -y

      - name: Build APK
        uses: digreatbrian/buildozer-action@v2
        with:
          buildozer-cmd: buildozer -v android debug
          work-dir: .

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: ./bin/*.apk
